const translations={
 en:{
  'nav.properties':'Properties','nav.projects':'Projects','nav.developers':'Developers','nav.compare':'Compare','nav.investment':'Investment','nav.about':'About JB','nav.cta':'Find My Property',
  'hero.eyebrow':'JB REAL ESTATE GROUP','hero.title':'Find. Compare. Decide. Invest.','hero.text':'Explore opportunities across Egypt, compare developers and projects, and get personalized guidance before you buy.','hero.primary':'Find My Property','hero.secondary':'Compare Projects','hero.note':'One market. Multiple options. One trusted partner.',
  'finder.eyebrow':'PROPERTY FINDER','finder.title':'Tell us what you are looking for.','finder.text':'Start with your priorities. We will use them to build a qualified shortlist.','finder.button':'Build My Shortlist',
  'fields.location':'Location','fields.budget':'Budget','fields.type':'Property type','fields.purpose':'Purpose','fields.delivery':'Delivery',
  'value.eyebrow':'WHY JB','value.title':'We are not here to show you one property. We help you understand your options.','value.text':'JB is being built as a real estate intelligence, advisory and brokerage platform: discover the market, compare alternatives, make a better-informed decision, then complete your purchase with JB.','value.link':'See how comparison works →','value.card1.title':'Multiple Options','value.card1.text':'Compare opportunities instead of relying on a single sales pitch.','value.card2.title':'Clear Sources','value.card2.text':'Track the source and freshness of important project information.','value.card3.title':'Personal Guidance','value.card3.text':'Move from search to a focused shortlist and advisor conversation.','value.card4.title':'Purchase Support','value.card4.text':'Keep the relationship with JB through the buying journey.',
  'projects.eyebrow':'EXPLORE','projects.title':'Projects','projects.link':'Find my best options →','projects.salt':'Example project profile — market data will be connected to verified sources in the next phase.','projects.cairo':'Project database for New Cairo opportunities will be added through the admin dashboard.','projects.coast':'Compare coastal projects by location, budget, payment plan and delivery.','common.view':'View profile →','common.explore':'Explore options →','common.compare':'Compare →',
  'developers.eyebrow':'MARKET DIRECTORY','developers.title':'Explore Developers','developers.text':'A structured directory designed to grow into a verified market intelligence database.','developers.search':'Search developer...','developers.searchBtn':'Search',
  'compare.eyebrow':'COMPARE BEFORE YOU BUY','compare.title':'One market. Clearer decisions.','compare.text':'The comparison engine will connect to the central database of developers, projects, prices, payment plans and delivery information.','compare.button':'Start a personalized search',
  'intl.eyebrow':'INTERNATIONAL BUYERS','intl.title':'Invest in Egypt with a clearer view of the market.','intl.text':'JB will provide English-first discovery, project comparison and buyer guidance for international clients interested in Egypt.','intl.li1':'Arabic + English from V1','intl.li2':'Investment-focused property search','intl.li3':'Transparent sources and update dates','intl.li4':'Personalized consultation','intl.button':'Request a consultation','intl.boxTitle':'Built for local and international buyers','intl.boxText':'The data model is designed to support multiple languages, currencies and future market modules such as land and commercial opportunities.',
  'cta.eyebrow':'READY TO START?','cta.title':'Tell JB what you want to buy.','cta.text':'We will turn your requirements into a focused property shortlist.','cta.button':'Build My Shortlist','footer.contact':'Contact','footer.social':'Social','footer.demo':'V1 prototype — market data modules are being connected.'
 },
 ar:{
  'nav.properties':'العقارات','nav.projects':'المشروعات','nav.developers':'المطورون','nav.compare':'مقارنة','nav.investment':'الاستثمار','nav.about':'عن JB','nav.cta':'ابحث عن عقارك',
  'hero.eyebrow':'مجموعة JB للعقارات','hero.title':'ابحث. قارن. اختر. استثمر.','hero.text':'اكتشف الفرص العقارية في مصر، وقارن بين المطورين والمشروعات، واحصل على توجيه يناسب احتياجاتك قبل الشراء.','hero.primary':'ابحث عن عقارك','hero.secondary':'قارن المشروعات','hero.note':'سوق واحد. خيارات متعددة. شريك واحد تثق به.',
  'finder.eyebrow':'الباحث العقاري','finder.title':'قل لنا ماذا تبحث عنه.','finder.text':'ابدأ باحتياجاتك، وسنستخدمها لبناء قائمة مختصرة مناسبة لك.','finder.button':'أنشئ قائمتي المختصرة',
  'fields.location':'الموقع','fields.budget':'الميزانية','fields.type':'نوع العقار','fields.purpose':'الهدف','fields.delivery':'التسليم',
  'value.eyebrow':'لماذا JB؟','value.title':'لسنا هنا لنعرض عليك عقارًا واحدًا. نحن نساعدك على فهم اختياراتك.','value.text':'نبني JB كمنصة للذكاء والاستشارات والوساطة العقارية: اكتشف السوق، قارن البدائل، اتخذ قرارًا أكثر وعيًا، ثم أكمل عملية الشراء من خلال JB.','value.link':'شاهد كيف تعمل المقارنة ←','value.card1.title':'خيارات متعددة','value.card1.text':'قارن الفرص بدل الاعتماد على عرض بيع واحد.','value.card2.title':'مصادر واضحة','value.card2.text':'تعرف على مصدر المعلومات ومدى حداثتها.','value.card3.title':'توجيه شخصي','value.card3.text':'انتقل من البحث إلى قائمة مختصرة وحوار مع مستشار.','value.card4.title':'دعم أثناء الشراء','value.card4.text':'تستمر علاقتك مع JB خلال رحلة الشراء.',
  'projects.eyebrow':'اكتشف','projects.title':'المشروعات','projects.link':'ابحث عن أفضل الخيارات ←','projects.salt':'صفحة تجريبية للمشروع — سيتم ربط بيانات السوق بمصادر موثقة في المرحلة التالية.','projects.cairo':'سيتم إضافة قاعدة بيانات مشروعات القاهرة الجديدة من خلال لوحة التحكم.','projects.coast':'قارن مشروعات الساحل حسب الموقع والميزانية والسداد والتسليم.','common.view':'عرض الصفحة ←','common.explore':'استكشف الخيارات ←','common.compare':'قارن ←',
  'developers.eyebrow':'دليل السوق','developers.title':'اكتشف المطورين','developers.text':'دليل منظم قابل للتحول إلى قاعدة بيانات للذكاء العقاري والتحقق من المعلومات.','developers.search':'ابحث عن مطور...','developers.searchBtn':'بحث',
  'compare.eyebrow':'قارن قبل أن تشتري','compare.title':'سوق واحد. قرارات أوضح.','compare.text':'سيتم ربط محرك المقارنة بقاعدة بيانات المطورين والمشروعات والأسعار وأنظمة السداد ومواعيد التسليم.','compare.button':'ابدأ بحثًا شخصيًا',
  'intl.eyebrow':'للمشترين الدوليين','intl.title':'استثمر في مصر برؤية أوضح للسوق.','intl.text':'ستوفر JB تجربة اكتشاف ومقارنة وإرشاد باللغة الإنجليزية للعملاء الدوليين المهتمين بالسوق المصري.','intl.li1':'العربية + الإنجليزية من الإصدار الأول','intl.li2':'بحث عقاري يركز على الاستثمار','intl.li3':'مصادر واضحة وتواريخ تحديث','intl.li4':'استشارة شخصية','intl.button':'اطلب استشارة','intl.boxTitle':'مصمم للعملاء المحليين والدوليين','intl.boxText':'تم تصميم نموذج البيانات لدعم اللغات والعملات المتعددة وإضافة وحدات مستقبلية مثل الأراضي والعقارات التجارية.',
  'cta.eyebrow':'جاهز للبدء؟','cta.title':'قل لـJB ماذا تريد أن تشتري.','cta.text':'سنحوّل احتياجاتك إلى قائمة مختصرة من الخيارات العقارية.','cta.button':'أنشئ قائمتي المختصرة','footer.contact':'تواصل معنا','footer.social':'تابعنا','footer.demo':'نموذج V1 — جاري تجهيز ربط وحدات بيانات السوق.'
 }
};
let lang='en';
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body.dir=document.documentElement.dir;document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{const k=el.dataset.i18nPlaceholder;if(translations[lang][k])el.placeholder=translations[lang][k]});document.getElementById('langToggle').textContent=lang==='en'?'العربية':'English';}
document.getElementById('langToggle').addEventListener('click',()=>{lang=lang==='en'?'ar':'en';applyLang()});
document.getElementById('year').textContent=new Date().getFullYear();
document.getElementById('finderForm').addEventListener('submit',e=>{e.preventDefault();const values={location:document.getElementById('location').value,budget:document.getElementById('budget').value,type:document.getElementById('type').value,purpose:document.getElementById('purpose').value,delivery:document.getElementById('delivery').value};const result=document.getElementById('finderResult');const filled=Object.values(values).filter(Boolean).length;result.hidden=false;result.innerHTML=lang==='en'?`<strong>Prototype result:</strong> ${filled?`We captured ${filled} preferences.`:'You can add preferences above.'} In the production version, this form will query the JB database and generate a qualified shortlist before asking for contact details.`:`<strong>نتيجة تجريبية:</strong> ${filled?`تم تسجيل ${filled} تفضيلات.`:'يمكنك إضافة تفضيلاتك أعلاه.'} في النسخة الفعلية سيبحث النموذج داخل قاعدة بيانات JB ويُنشئ قائمة مختصرة قبل طلب بيانات التواصل.`;result.scrollIntoView({behavior:'smooth',block:'nearest'})});
applyLang();
